import '@radix-ui/themes/styles.css';
import type { Metadata } from 'next';
import './globals.css';
import NavBar from './NavBar';
import { Container, Theme } from '@radix-ui/themes';
import AuthProvider from './auth/Provider';
import QueryClientProvider from './QueryClientProvider';
// import { Inter } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      {/* <body className={`${inter.variable} antialiased`}> */}
      <body className={` antialiased`}>
        <QueryClientProvider>
          <AuthProvider>
            <Theme appearance='light' accentColor='plum' radius='full'>
              <nav>
                <NavBar />
              </nav>
              <main className='p-5'>
                <Container>{children}</Container>
              </main>
            </Theme>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
